export default {
    products: [
        {
            _id: '3244',
            name: 'Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 60,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
        },
        {
            _id: '3234544',
            name: 'Fit Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 990,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
        },
        {
            _id: '324464564',
            name: 'Best Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 90,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
        },
        {
            _id: '324234244',
            name: 'Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
        },
        {
            _id: '329879744',
            name: 'Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 50,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
        },
    ],
};
